# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bivariate_choropleth',
                'doc_host': 'https://Parkes2.github.io',
                'git_url': 'https://github.com/Parkes2/bivariate_choropleth',
                'lib_path': 'bivariate_choropleth'},
  'syms': {'bivariate_choropleth.core': {'bivariate_choropleth.core.foo': ('core.html#foo', 'bivariate_choropleth/core.py')}}}
